{{date.DATA}} 
{{zao.DATA}}
当前城市：{{region.DATA}}
今日天气：{{weather.DATA}}  {{pop.DATA}}
当前气温：{{temp.DATA}}  
最高气温：{{highest.DATA}} 
最低气温：{{lowest.DATA}}
风向：{{wind_dir.DATA}} {{tips.DATA}}
今天是我们相恋的第{{love_day.DATA}}天
{{birthday1.DATA}}
{{birthday2.DATA}}
{{lucky.DATA}}
{{note_en.DATA}}
{{pipi.DATA}}

